In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6625, 4868, 6696, 5396],
 [6625, 4868, 6696, 7576],
 [6625, 9402, 6696, 2164],
 [2428, 121, 1175, 506, 6616],
 [2428, 121, 1175, 506, 103],
 [3725, 6625, 8741, 6696, 3586],
 [3475, 9798, 1229, 506]]

In [16]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding , Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [ ]:
sent_length=8
## Padding the sequences to have same length
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6625 4868 6696 5396]
 [   0    0    0    0 6625 4868 6696 7576]
 [   0    0    0    0 6625 9402 6696 2164]
 [   0    0    0 2428  121 1175  506 6616]
 [   0    0    0 2428  121 1175  506  103]
 [   0    0    0 3725 6625 8741 6696 3586]
 [   0    0    0    0 3475 9798 1229  506]]


In [13]:
## feature representation
dim=10

In [18]:
model = Sequential()

model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))

model.compile(optimizer='adam', loss='mse')

In [19]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[[-1.69073716e-02, -1.68249980e-02, -2.33737584e-02,
         -1.41126737e-02, -2.28586551e-02, -4.17791232e-02,
         -6.31292909e-03,  3.39341648e-02,  2.63842680e-02,
         -7.11679459e-05],
        [-1.69073716e-02, -1.68249980e-02, -2.33737584e-02,
         -1.41126737e-02, -2.28586551e-02, -4.17791232e-02,
         -6.31292909e-03,  3.39341648e-02,  2.63842680e-02,
         -7.11679459e-05],
        [-1.69073716e-02, -1.68249980e-02, -2.33737584e-02,
         -1.41126737e-02, -2.28586551e-02, -4.17791232e-02,
         -6.31292909e-03,  3.39341648e-02,  2.63842680e-02,
         -7.11679459e-05],
        [-1.69073716e-02, -1.68249980e-02, -2.33737584e-02,
         -1.41126737e-02, -2.28586551e-02, -4.17791232e-02,
         -6.31292909e-03,  3.39341648e-02,  2.63842680e-02,
         -7.11679459e-05],
        [-4.33700457e-02,  4.09814008e-02,  6.64073229e-03,
          4.99427356e-02, -3.45212594e-02, -4.06202674e-02,
          2.19785683e-02, -3.26211452e-02, -2.350412

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 6625, 4868, 6696, 5396], dtype=int32)